branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: AWSDjangoApp
  branch: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
